# Site settings
title: Hugo MATilla GÓMez
email: hugomatilla@gmail.com
description: Code and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matgom.com" # the base hostname & protocol for your site
twitter_username: hugomatgom	
github_username:  hugomatilla

# Build settings
markdown: kramdown
